### ISSUE TITLE
refactor Part 3 

### ISSUE THREAD

**Issue by tonyewong** [MUSSLES/tutorials#2]
Refactor Part 3 (distribution fitting) tutorial into:

**Part 2:** fitting normal distribution using synthetic data, known parameters, and showing we cna recover the known parameters using MCMC.
- Segue: central limit theorem gives normal distribution as the limiting distribution for a sequence of means... but what about maxima? When dealing with extreme sea levels, we are concerned about maxima!
- The limiting distribution for that is a generalized extreme value distribution
- fitting GEV using synthetic data, showing we can recover the known paraemters using MCMC

**Part 3:** fitting unknown GEV distribution parameters using MCMC and a tide gauge site. Just one site is enough, preferably US gulf coast (pensacola? galveston?

**Part 4** will be the sea-level rise model from Nihar. But these other two sections seem like they're moving along faster, so let's keep them sequential.

**Comment by jletey** [comment]
I think we've done just about this, so I'm going to go ahead and close this!
